### ISSUE TITLE
julkaisu lomakkeen kentät

### ISSUE THREAD

**Issue by oernantti** [gaissa/Raito#11]
maa kenttä pois, muut kentät on:
Alue = aluelautakunnat: http://www.rovaniemi.fi/fi/Palvelut/Kylat-ja-kaupunginosat/Aluelautakunnat
Kylän = voi kirjoittaa itse pitäisikö nimetä kylä tai kaupunginosa
Kaupunginosa = turha ajaa samaa asiaa ku kylä?
Katuosoite = tästä mapsi sitten hakkee oikean pisteen kartalle?

**Comment by gaissa** [comment]
@oernantti Onko nää nyt ok?

**Comment by oernantti** [comment]
Miten se aikahomma?

**Comment by gaissa** [comment]
@oernantti Aikahomma jees. Tää pitää kahtoa uusiksi myöhemmin jos tulee jotain.
