### ISSUE TITLE
proper region names

### ISSUE THREAD

**Issue by oernantti** [gaissa/Raito#2]
- Yläounasjoki
-  Alaounasjoki
-  Yläkemijoki
-  Alakemijoki
-  Sodankyläntien suunta
-  Ranuantien suunta

**Comment by gaissa** [comment]
Keskusta? Rovaniemi?

**Comment by oernantti** [comment]
Rovanieme keskus - says on the map

**Comment by gaissa** [comment]
[](https://github.com/gaissa/Raito/blob/master/install-scripts/locations.sql)

**Comment by gaissa** [comment]
Just clean this up and update if needed.

**Comment by gaissa** [comment]
https://github.com/gaissa/Raito/blob/master/install-scripts/locations.sql
