### ISSUE TITLE
Funny translations :)

### ISSUE THREAD

**Issue by gaissa** [gaissa/Raito#20]
**tilini = tilin asetukset? asetukset?**

adminipuolen käännöksiä karsii sitten kans ku ehtii. Ei toimi enkuksi oikeen...

**Comment by oernantti** [comment]
tilin asetukset ok


ändatum datum = ilmoituksen pättymisaika / päivämäärä

**Comment by oernantti** [comment]
click or drop for upload images = klikkaa tai vedä ja pudota ladataksesi kuvatiedoston

**Comment by oernantti** [comment]
yleistä tietoa = ilmoituksen tiedot

**Comment by gaissa** [comment]
Tuo yleistä tietoa vois heivata kokonaan pois. Se on aika selkee että se on yleistä tietoa. ja kuvan uppauksen käännökset on plugarissa, joten ne pittää erikseen täsä kun kerkee :)

**Comment by gaissa** [comment]
**Tämä on oma listauksesi et voi ottaa yhteyttä julkaisijaan**

Mitenhän tuo. Vois tuohon tulla jotai muutakin. Ainaki tuo käännös kuntoon jos ei vielä muuta.

**Comment by gaissa** [comment]
Jea. Siihen tosiaan vois keksiä jottain järkevämpääkin tilalle.

**Comment by oernantti** [comment]
fixed allready?

**Comment by gaissa** [comment]
@oernantti Jöös. Lisätään erikseen ku tulee vastaan jotain.
