### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by oernantti** [gaissa/Raito#24]
useless in "julkaise" funktions

**Comment by gaissa** [comment]
Got to fix this... any other pages?

**Comment by gaissa** [comment]
@oernantti Should I fix this? We can test the site without it on some sections, but personally I like it to be all around if feeling lazy as there is no direct link to categories and such anywhere else.

**Comment by oernantti** [comment]
if it doesn't cause too muc scrolling or inconvenience with mobile, it's cool.. so you dont have to go all the way back to the frontpage to do another search... approved seearch can be on every scene but not the banner roight

**Comment by gaissa** [comment]
allright :dart: :+1:
