### ISSUE TITLE
Ajankohtaista - kategoria enhancement

### ISSUE THREAD

**Issue by oernantti** [gaissa/Raito#7]
Ajankohtaista kategoria ?

**Comment by gaissa** [comment]
Ilmotukset voidaan merkitä "premium" tilaan, ja se toimii hyvin ajankohtaista kategoriana eikös?

**Comment by gaissa** [comment]
Tää on hyvä. Jos esiintyy tuplana jossain niin siitä sitten issueta kehiin.
