### ISSUE TITLE
muutos kategoriat = palvelut ja työt

### ISSUE THREAD

**Issue by oernantti** [gaissa/Raito#8]
kategoria sana vaihtuu palvelut työt

**Comment by gaissa** [comment]
Tän voit tehä käännöksiin esim, löytynee sieltä teeman .po -tiedostosta. Tsekkaan koodipuolen.

**Comment by gaissa** [comment]
Etusivulla on ainakin vielä Kategoriat otsikko. Onkohan muualla?

**Comment by gaissa** [comment]
Valamista. Jos ilmenee vielä nii uutta issueta niistä sitte esim.
